INFO 2022-06-30 13:15:19,624 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:15:27,521 basehttp 187 "GET / HTTP/1.1" 200 10697
INFO 2022-06-30 13:15:27,595 basehttp 187 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2022-06-30 13:15:27,711 basehttp 187 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2022-06-30 13:15:27,712 basehttp 187 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2022-06-30 13:15:27,712 basehttp 187 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
WARNING 2022-06-30 13:15:27,788 log 241 Not Found: /favicon.ico
WARNING 2022-06-30 13:15:27,788 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 2117
INFO 2022-06-30 13:16:03,468 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:16:52,718 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 13:16:53,045 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:16:58,991 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:17:16,209 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:18:33,184 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\models.py changed, reloading.
INFO 2022-06-30 13:18:33,555 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:18:50,020 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\models.py changed, reloading.
INFO 2022-06-30 13:18:50,366 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:19:11,324 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:19:32,218 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:19:39,169 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:19:53,764 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:20:01,164 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 13:20:01,511 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:20:55,888 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 13:20:56,228 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:21:07,634 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 13:21:07,984 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:25:59,152 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:26:23,721 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:27:00,580 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:29:12,766 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 13:29:13,172 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 13:29:47,150 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 13:29:47,519 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:17:41,209 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:18:09,052 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:18:09,428 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:19:01,831 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:19:02,187 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:19:08,572 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:19:08,917 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:19:28,582 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:19:28,955 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:19:43,547 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:19:43,920 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:20:17,919 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:20:18,318 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-06-30 15:22:53,836 log 241 Internal Server Error: /usernames/hjx/count
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.users.views.view didn't return an HttpResponse object. It returned None instead.
ERROR 2022-06-30 15:22:53,837 basehttp 187 "GET /usernames/hjx/count HTTP/1.1" 500 66569
INFO 2022-06-30 15:23:30,086 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:23:32,173 basehttp 187 "GET /usernames/hjx/count HTTP/1.1" 200 12
INFO 2022-06-30 15:24:21,508 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 15:24:21,864 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:24:32,268 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 15:24:32,654 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:27:19,997 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 15:27:20,390 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:27:25,464 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:27:28,925 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 15:27:32,947 log 241 Not Found: /usernames/hjx/count
WARNING 2022-06-30 15:27:32,948 basehttp 187 "GET /usernames/hjx/count HTTP/1.1" 404 2335
INFO 2022-06-30 15:27:41,829 basehttp 187 "GET /usernames/hejiaxin/count HTTP/1.1" 200 12
INFO 2022-06-30 15:29:16,510 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:31:34,723 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 15:31:37,685 log 241 Not Found: /image_codes/77e51837-916f-4456-8513-0e5698133bba/
WARNING 2022-06-30 15:31:37,686 basehttp 187 "GET /image_codes/77e51837-916f-4456-8513-0e5698133bba/ HTTP/1.1" 404 2425
WARNING 2022-06-30 15:31:40,344 log 241 Not Found: /usernames/afefea/count/
WARNING 2022-06-30 15:31:40,345 basehttp 187 "GET /usernames/afefea/count/ HTTP/1.1" 404 2347
INFO 2022-06-30 15:32:28,171 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:32:28,487 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:33:11,366 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:33:11,756 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:33:41,544 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:36:47,252 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 15:36:50,607 log 241 Not Found: /image_codes/eb1dbaee-78c1-4258-a5a8-d087469e7754/
WARNING 2022-06-30 15:36:50,607 basehttp 187 "GET /image_codes/eb1dbaee-78c1-4258-a5a8-d087469e7754/ HTTP/1.1" 404 2425
WARNING 2022-06-30 15:36:53,139 log 241 Not Found: /usernames/srgrshgsrer/count/
WARNING 2022-06-30 15:36:53,139 basehttp 187 "GET /usernames/srgrshgsrer/count/ HTTP/1.1" 404 2362
INFO 2022-06-30 15:37:34,177 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 15:37:39,632 log 241 Not Found: /image_codes/1053d7f2-75e5-48e8-943b-4873d09c7ff3/
WARNING 2022-06-30 15:37:39,633 basehttp 187 "GET /image_codes/1053d7f2-75e5-48e8-943b-4873d09c7ff3/ HTTP/1.1" 404 2426
INFO 2022-06-30 15:37:42,841 basehttp 187 "GET /usernames/aegfaegae/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:37:50,236 basehttp 187 "GET /usernames/aegfaegae/count/ HTTP/1.1" 200 12
WARNING 2022-06-30 15:37:50,397 log 241 Not Found: /favicon.ico
WARNING 2022-06-30 15:37:50,398 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 2312
WARNING 2022-06-30 15:37:57,487 log 241 Not Found: /image_codes/a995954a-e384-428d-bedb-811fc9d66989/
WARNING 2022-06-30 15:37:57,488 basehttp 187 "GET /image_codes/a995954a-e384-428d-bedb-811fc9d66989/ HTTP/1.1" 404 2426
INFO 2022-06-30 15:37:59,931 basehttp 187 "GET /usernames/sdgeg/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:38:35,486 basehttp 187 "GET /usernames/sdgegsdgte/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:39:19,320 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 15:39:22,372 log 241 Not Found: /image_codes/a5465598-90e0-4fc0-af15-e848e6d5cb41/
WARNING 2022-06-30 15:39:22,373 basehttp 187 "GET /image_codes/a5465598-90e0-4fc0-af15-e848e6d5cb41/ HTTP/1.1" 404 2426
INFO 2022-06-30 15:39:24,595 basehttp 187 "GET /usernames/ewsgesg/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:40:26,043 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:40:26,426 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:40:55,120 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:41:00,758 basehttp 187 "GET /usernames/ewsgesgs/count/ HTTP/1.1" 200 12
WARNING 2022-06-30 15:41:03,828 log 241 Not Found: /image_codes/f7dd2e32-2246-4092-862a-f2380c1eab0f/
WARNING 2022-06-30 15:41:03,828 basehttp 187 "GET /image_codes/f7dd2e32-2246-4092-862a-f2380c1eab0f/ HTTP/1.1" 404 2426
INFO 2022-06-30 15:41:06,987 basehttp 187 "GET /usernames/aaaaa/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:41:41,372 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:41:41,758 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:47:38,291 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:47:54,929 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:48:19,133 basehttp 187 "GET /mobiles/13345678901/count/ HTTP/1.1" 200 12
INFO 2022-06-30 15:48:49,313 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 15:48:49,721 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:49:12,385 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-06-30 15:49:12,766 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:50:28,625 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:52:48,497 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:52:48,853 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:54:05,552 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:54:05,939 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:54:59,277 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:54:59,658 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:55:03,992 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:55:04,360 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:55:34,166 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:55:34,548 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:56:10,482 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:56:10,856 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:57:14,366 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:57:14,757 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:58:01,906 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 15:58:02,299 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 15:59:15,953 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 15:59:16,317 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:00:26,899 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 16:00:27,285 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-06-30 16:03:27,445 log 241 Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 45, in register
    elif User.objects.filter(phone=mobile).count():
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1377, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1187, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'phone' into field. Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, mobile, password, user_permissions, username
ERROR 2022-06-30 16:03:27,447 basehttp 187 "POST /register/ HTTP/1.1" 500 111461
INFO 2022-06-30 16:03:50,850 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-06-30 16:03:54,204 log 241 Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 50, in register
    user = User.objects.create_user(username=username, password=password, phone=mobile)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\models.py", line 160, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\models.py", line 152, in _create_user
    user = self.model(username=username, email=email, **extra_fields)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: User() got an unexpected keyword argument 'phone'
ERROR 2022-06-30 16:03:54,205 basehttp 187 "POST /register/ HTTP/1.1" 500 83096
INFO 2022-06-30 16:04:19,231 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:04:21,314 basehttp 187 "POST /register/ HTTP/1.1" 200 27
INFO 2022-06-30 16:06:44,555 basehttp 187 "GET /usernames/hejiaxin/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:06:48,473 basehttp 187 "GET /usernames/hejiaxin/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:06:51,784 basehttp 187 "GET /usernames/hejiaxin/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:06:56,664 basehttp 187 "GET /usernames/skxmxm/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:07:09,473 basehttp 187 "GET /usernames/skxmxm/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:07:09,475 basehttp 187 "GET /mobiles/13345678901/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:07:10,563 basehttp 187 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2022-06-30 16:07:10,565 basehttp 187 "GET /mobiles/13345678901/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:07:10,573 basehttp 187 "GET /usernames/skxmxm/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:07:10,696 basehttp 187 "POST /register/ HTTP/1.1" 200 27
WARNING 2022-06-30 16:07:10,970 log 241 Not Found: /carts/simple/
WARNING 2022-06-30 16:07:10,970 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 2657
INFO 2022-06-30 16:10:13,864 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 16:10:14,278 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-06-30 16:10:54,575 log 241 Not Found: /image_codes/a479e3e8-83a6-415d-95d8-68f78b35a51f/
WARNING 2022-06-30 16:10:54,575 basehttp 187 "GET /image_codes/a479e3e8-83a6-415d-95d8-68f78b35a51f/ HTTP/1.1" 404 2765
INFO 2022-06-30 16:10:58,433 basehttp 187 "GET /usernames/asdfg/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:14:14,567 basehttp 187 "GET /mobiles/13345678994/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:14:21,531 basehttp 187 "GET /usernames/asdfg/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:14:21,537 basehttp 187 "GET /mobiles/13345678994/count/ HTTP/1.1" 200 12
INFO 2022-06-30 16:14:21,680 basehttp 187 "POST /register/ HTTP/1.1" 200 27
WARNING 2022-06-30 16:14:21,931 log 241 Not Found: /carts/simple/
WARNING 2022-06-30 16:14:21,932 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 2657
WARNING 2022-06-30 16:18:34,690 log 241 Not Found: /image_codes/1040f2d6-7715-43b2-9304-28ef711875ca/
WARNING 2022-06-30 16:18:34,690 basehttp 187 "GET /image_codes/1040f2d6-7715-43b2-9304-28ef711875ca/ HTTP/1.1" 404 2765
INFO 2022-06-30 16:20:00,563 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-06-30 16:20:00,982 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:25:18,535 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-06-30 16:25:18,969 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:44:13,370 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:45:07,863 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:45:29,723 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:45:33,964 basehttp 187 "GET /image_codes/a7944332-c5b0-4174-9a4a-d17b29b14476/ HTTP/1.1" 200 2832
INFO 2022-06-30 16:45:35,472 basehttp 187 "GET /image_codes/f2821aa0-dd94-4a11-94c9-33cc3f996b7e/ HTTP/1.1" 200 2373
INFO 2022-06-30 16:45:36,402 basehttp 187 "GET /image_codes/da5bdc07-4601-465e-a2d6-5e620c7aad7a/ HTTP/1.1" 200 2544
INFO 2022-06-30 16:45:38,253 basehttp 187 "GET /image_codes/f7dcbe40-f511-4338-960b-42e9a7abd8f5/ HTTP/1.1" 200 2893
INFO 2022-06-30 16:45:40,555 basehttp 187 "GET /image_codes/099de598-05a8-4e32-b949-849aebd3abee/ HTTP/1.1" 200 2742
INFO 2022-06-30 16:46:58,343 autoreload 677 Watching for file changes with StatReloader
INFO 2022-06-30 16:47:02,557 basehttp 187 "GET /image_codes/6eb78ce1-c149-4f65-87c4-5a480461ce53/ HTTP/1.1" 200 2457
INFO 2022-06-30 16:47:03,913 basehttp 187 "GET /image_codes/986857e3-453f-4fb4-be5f-697bc34fc594/ HTTP/1.1" 200 2852
INFO 2022-06-30 16:47:09,300 basehttp 187 "GET /image_codes/a9e3acd7-62a6-40a3-9511-8c065790a31b/ HTTP/1.1" 200 2473
INFO 2022-07-01 13:54:07,874 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 13:54:10,801 basehttp 187 "GET /image_codes/d24710f8-800d-48dc-84d0-75eaefc03a22/ HTTP/1.1" 200 2694
INFO 2022-07-01 13:54:16,887 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
ERROR 2022-07-01 13:54:17,124 log 241 Internal Server Error: /sms_codes/13576154277/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.verifications.views.sms_check didn't return an HttpResponse object. It returned None instead.
ERROR 2022-07-01 13:54:17,125 basehttp 187 "GET /sms_codes/13576154277/?image_code=h3a9v&image_code_id=d24710f8-800d-48dc-84d0-75eaefc03a22 HTTP/1.1" 500 69337
INFO 2022-07-01 13:54:20,716 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 13:54:21,726 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
ERROR 2022-07-01 13:54:21,928 log 241 Internal Server Error: /sms_codes/13576154277/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.verifications.views.sms_check didn't return an HttpResponse object. It returned None instead.
ERROR 2022-07-01 13:54:21,928 basehttp 187 "GET /sms_codes/13576154277/?image_code=h3a9v&image_code_id=d24710f8-800d-48dc-84d0-75eaefc03a22 HTTP/1.1" 500 69337
INFO 2022-07-01 13:54:27,166 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 13:54:27,855 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
ERROR 2022-07-01 13:54:28,058 log 241 Internal Server Error: /sms_codes/13576154277/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.verifications.views.sms_check didn't return an HttpResponse object. It returned None instead.
ERROR 2022-07-01 13:54:28,060 basehttp 187 "GET /sms_codes/13576154277/?image_code=h3a9v&image_code_id=d24710f8-800d-48dc-84d0-75eaefc03a22 HTTP/1.1" 500 69337
INFO 2022-07-01 13:56:28,599 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 13:58:27,665 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 13:58:27,865 basehttp 187 "GET /sms_codes/13576154277/?image_code=h3a9v&image_code_id=d24710f8-800d-48dc-84d0-75eaefc03a22 HTTP/1.1" 200 2
INFO 2022-07-01 13:59:19,590 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 13:59:28,542 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 13:59:28,690 basehttp 187 "GET /sms_codes/13576154277/?image_code=h3a9v&image_code_id=d24710f8-800d-48dc-84d0-75eaefc03a22 HTTP/1.1" 200 2
INFO 2022-07-01 13:59:53,785 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 13:59:59,934 basehttp 187 "GET /image_codes/7441936d-f812-4cef-adba-2eecf3193f38/ HTTP/1.1" 200 2571
INFO 2022-07-01 14:00:03,807 basehttp 187 "GET /usernames/skxmxm/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:00:06,523 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:00:14,242 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:00:19,945 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:00:20,132 basehttp 187 "GET /sms_codes/13576154277/?image_code=k97in&image_code_id=7441936d-f812-4cef-adba-2eecf3193f38 HTTP/1.1" 200 2
INFO 2022-07-01 14:02:24,261 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:02:24,622 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:03:09,525 basehttp 187 "GET /image_codes/35364372-e78b-4f1f-8f90-561c42a16e5c/ HTTP/1.1" 200 2931
INFO 2022-07-01 14:03:13,996 basehttp 187 "GET /image_codes/eab74791-ff26-4799-978c-44d8d5b8c393/ HTTP/1.1" 200 2746
INFO 2022-07-01 14:04:05,692 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:04:06,104 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:05:27,486 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:05:27,858 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:06:16,025 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:06:16,400 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:07:23,455 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:07:23,830 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:08:57,453 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:08:57,858 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:10:33,599 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\urls.py changed, reloading.
INFO 2022-07-01 14:10:34,053 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:11:16,480 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:11:16,862 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:11:33,438 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:11:33,840 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:11:42,416 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:11:42,815 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:12:24,262 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:12:24,647 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:12:57,824 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:12:58,220 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:13:09,819 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:13:10,160 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:13:37,111 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:13:37,555 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:14:07,611 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:14:08,004 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:14:32,990 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:14:33,384 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:16:18,427 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:16:18,794 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:17:34,030 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:17:34,477 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:17:39,982 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-01 14:17:40,383 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:17:47,592 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:19:10,814 basehttp 187 "GET /image_codes/0bf5e7b8-bdde-4d86-a954-36d30372957d/ HTTP/1.1" 200 2909
INFO 2022-07-01 14:19:28,577 basehttp 187 "GET /sms_codes/13576154277/?image_code=two6u&image_code_id=0bf5e7b8-bdde-4d86-a954-36d30372957d HTTP/1.1" 200 69
INFO 2022-07-01 14:19:28,579 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:20:40,560 basehttp 187 "GET /sms_codes/13576154277/?image_code=two6u&image_code_id=0bf5e7b8-bdde-4d86-a954-36d30372957d HTTP/1.1" 200 69
INFO 2022-07-01 14:20:40,560 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:22:33,521 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:22:38,116 basehttp 187 "GET /image_codes/02454d04-5a31-4d80-8a77-dffa638b2e44/ HTTP/1.1" 200 2381
INFO 2022-07-01 14:22:41,898 basehttp 187 "GET /image_codes/5781c02d-cba8-4ede-9862-af3cf435c157/ HTTP/1.1" 200 2457
INFO 2022-07-01 14:22:46,180 basehttp 187 "GET /sms_codes/13576154277/?image_code=piwxk&image_code_id=5781c02d-cba8-4ede-9862-af3cf435c157 HTTP/1.1" 200 69
INFO 2022-07-01 14:22:46,185 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:23:03,799 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:23:11,541 basehttp 187 "GET /image_codes/c6e7a98e-6122-4370-bc33-d73615fc96bb/ HTTP/1.1" 200 2128
INFO 2022-07-01 14:23:14,392 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:23:21,143 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:23:25,808 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:24:36,736 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:24:42,059 basehttp 187 "GET /image_codes/b892fae5-1557-4c7c-b83f-66562c49d564/ HTTP/1.1" 200 2318
INFO 2022-07-01 14:25:17,236 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:25:26,206 basehttp 187 "GET /image_codes/3ffd14ef-b2d4-4713-86e1-89ee3047d174/ HTTP/1.1" 200 2658
INFO 2022-07-01 14:25:33,613 basehttp 187 "GET /image_codes/a57d0837-00e0-44b1-a1ea-ac4e2488ddc9/ HTTP/1.1" 200 2962
INFO 2022-07-01 14:25:36,557 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:25:43,399 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:25:49,555 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:26:54,997 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:27:11,829 basehttp 187 "GET /image_codes/4468685a-c71e-4fdf-8188-8f83197a3de0/ HTTP/1.1" 200 2896
INFO 2022-07-01 14:27:15,304 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:27:21,581 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:27:26,933 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:27:39,261 basehttp 187 "GET /image_codes/4a8714db-ae35-4430-aa24-1d48667d8fab/ HTTP/1.1" 200 2040
INFO 2022-07-01 14:27:44,241 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:27:47,656 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:27:57,911 basehttp 187 "GET /image_codes/faebdbb3-0205-410c-8d5f-bdc92c3fb3d4/ HTTP/1.1" 200 2589
INFO 2022-07-01 14:28:00,239 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:28:08,613 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:28:10,580 basehttp 187 "GET /image_codes/9970c9c8-9be0-40e5-a720-cbf1c2cc18e6/ HTTP/1.1" 200 2432
INFO 2022-07-01 14:28:13,154 basehttp 187 "GET /image_codes/c2a8c342-676d-4221-87f1-75333e8508bb/ HTTP/1.1" 200 2640
INFO 2022-07-01 14:28:17,211 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:28:26,216 basehttp 187 "GET /sms_codes/13576154277/?image_code=lbk3v&image_code_id=c2a8c342-676d-4221-87f1-75333e8508bb HTTP/1.1" 200 27
INFO 2022-07-01 14:28:53,726 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:29:01,838 basehttp 187 "GET /image_codes/d37360e5-ed01-4fb1-b8e1-5c0524e34a8d/ HTTP/1.1" 200 2708
INFO 2022-07-01 14:29:04,946 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:29:09,236 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:29:12,776 basehttp 187 "GET /image_codes/ee1a3665-3bf4-4457-8d21-dccc12457c72/ HTTP/1.1" 200 2981
INFO 2022-07-01 14:29:19,870 basehttp 187 "GET /sms_codes/13576154277/?image_code=udbic&image_code_id=ee1a3665-3bf4-4457-8d21-dccc12457c72 HTTP/1.1" 200 27
INFO 2022-07-01 14:29:19,870 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:30:17,500 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:30:21,064 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:30:21,202 basehttp 187 "GET /sms_codes/13576154277/?image_code=udbic&image_code_id=ee1a3665-3bf4-4457-8d21-dccc12457c72 HTTP/1.1" 200 27
INFO 2022-07-01 14:31:29,856 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-01 14:31:30,261 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:42:15,301 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-01 14:42:15,717 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:47:31,435 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:47:44,578 basehttp 187 "GET /image_codes/3b975ded-842d-4ea0-8851-2abfaf5b37ed/ HTTP/1.1" 200 2456
INFO 2022-07-01 14:47:47,465 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:47:53,529 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:47:55,593 basehttp 187 "GET /image_codes/d9e926b4-4370-44ad-9b86-35c6e5c3839a/ HTTP/1.1" 200 2634
INFO 2022-07-01 14:48:01,214 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:48:01,358 basehttp 187 "GET /sms_codes/13576154277/?image_code=syq5t&image_code_id=d9e926b4-4370-44ad-9b86-35c6e5c3839a HTTP/1.1" 200 27
INFO 2022-07-01 14:53:09,863 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-01 14:58:32,348 basehttp 187 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2022-07-01 14:58:32,355 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:58:32,355 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-01 14:58:32,362 basehttp 187 "POST /register/ HTTP/1.1" 200 50
INFO 2022-07-02 12:50:43,424 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-02 12:51:30,538 log 241 Not Found: /carts/simple/
WARNING 2022-07-02 12:51:30,538 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3008
INFO 2022-07-02 12:51:32,397 basehttp 187 "GET /image_codes/72cc09b4-9ff6-4941-b4b5-21fcf94111ba/ HTTP/1.1" 200 2559
INFO 2022-07-02 12:51:35,781 basehttp 187 "GET /usernames/skxmxm/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:51:40,770 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:51:48,835 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:51:57,346 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:51:57,570 basehttp 187 "GET /sms_codes/13576154277/?image_code=pzavm&image_code_id=72cc09b4-9ff6-4941-b4b5-21fcf94111ba HTTP/1.1" 200 27
INFO 2022-07-02 12:52:07,316 basehttp 187 "GET /image_codes/e775d25c-a6d7-4721-9316-10c4b43b5a79/ HTTP/1.1" 200 2727
INFO 2022-07-02 12:52:11,332 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:52:17,073 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:52:17,506 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 12:52:20,811 basehttp 187 "GET /sms_codes/13576154277/?image_code=k4leg&image_code_id=e775d25c-a6d7-4721-9316-10c4b43b5a79 HTTP/1.1" 200 63
INFO 2022-07-02 12:52:20,823 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 13:03:07,625 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 13:03:08,058 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:03:31,825 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 13:03:32,215 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:03:49,956 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 13:03:50,336 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:03:52,739 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 13:03:53,089 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:04:04,671 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 13:04:05,050 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:27:47,728 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:34:10,518 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:43:14,975 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 13:43:18,884 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 14:19:01,308 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 14:19:29,795 basehttp 187 "GET /image_codes/93ea202f-0935-4104-8c3d-4deae472071e/ HTTP/1.1" 200 2912
INFO 2022-07-02 14:19:35,233 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 14:19:35,385 basehttp 187 "GET /sms_codes/13576154277/?image_code=i3bgf&image_code_id=93ea202f-0935-4104-8c3d-4deae472071e HTTP/1.1" 200 27
INFO 2022-07-02 14:22:51,656 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-02 14:22:52,129 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-02 14:29:25,817 basehttp 187 "GET /image_codes/255eb1a0-73b7-4c9f-85bd-956978a6fa30/ HTTP/1.1" 200 2809
INFO 2022-07-02 14:29:31,613 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-02 14:29:31,749 basehttp 187 "GET /sms_codes/13576154277/?image_code=ey2u4&image_code_id=255eb1a0-73b7-4c9f-85bd-956978a6fa30 HTTP/1.1" 200 27
INFO 2022-07-03 13:16:59,063 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:18:12,266 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:18:19,449 basehttp 187 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2022-07-03 13:18:19,455 basehttp 187 "POST /login/ HTTP/1.1" 200 44
INFO 2022-07-03 13:18:29,524 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:19:00,503 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:19:47,817 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:20:01,446 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:20:16,476 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:20:21,344 basehttp 187 "POST /login/ HTTP/1.1" 200 75
INFO 2022-07-03 13:20:33,054 basehttp 187 "GET /image_codes/0920724c-f93f-4e11-adbb-e2a59a3fe447/ HTTP/1.1" 200 2510
INFO 2022-07-03 13:20:35,712 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:20:50,278 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:20:53,949 basehttp 187 "GET /image_codes/f8bbf754-1048-4407-99cb-4d37d27aaf14/ HTTP/1.1" 200 2766
INFO 2022-07-03 13:20:58,209 basehttp 187 "GET /sms_codes/13576154277/?image_code=asm7z&image_code_id=f8bbf754-1048-4407-99cb-4d37d27aaf14 HTTP/1.1" 200 69
INFO 2022-07-03 13:20:58,224 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:33,349 basehttp 187 "GET /image_codes/43fe59c4-ffd8-4198-bb3f-f5b4484c0cdc/ HTTP/1.1" 200 2653
INFO 2022-07-03 13:24:38,723 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:38,790 basehttp 187 "GET /sms_codes/13576154277/?image_code=y4qvd&image_code_id=43fe59c4-ffd8-4198-bb3f-f5b4484c0cdc HTTP/1.1" 200 27
INFO 2022-07-03 13:24:49,149 basehttp 187 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2022-07-03 13:24:49,150 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:49,151 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:49,157 basehttp 187 "POST /register/ HTTP/1.1" 200 50
INFO 2022-07-03 13:24:55,105 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:55,105 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:24:55,107 basehttp 187 "POST /register/ HTTP/1.1" 200 50
INFO 2022-07-03 13:25:23,137 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:25:26,965 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:25:26,965 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:25:55,306 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:25:56,174 basehttp 187 "GET /usernames/skxmxm1/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:25:56,184 basehttp 187 "GET /mobiles/13576154277/count/ HTTP/1.1" 200 12
INFO 2022-07-03 13:26:05,997 basehttp 187 "POST /register/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:26:06,386 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:26:06,387 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
WARNING 2022-07-03 13:26:24,122 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:26:24,122 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
WARNING 2022-07-03 13:26:35,419 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:26:35,420 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 13:26:51,743 basehttp 187 "POST /login/ HTTP/1.1" 200 75
INFO 2022-07-03 13:27:07,036 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:28:02,519 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-03 13:28:09,483 log 241 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.users.views.user_login didn't return an HttpResponse object. It returned None instead.
ERROR 2022-07-03 13:28:09,484 basehttp 187 "POST /login/ HTTP/1.1" 500 68646
INFO 2022-07-03 13:28:44,172 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:28:46,287 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:28:46,464 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:28:46,464 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 13:29:16,204 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:29:16,372 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:29:16,372 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 13:29:36,460 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:30:07,038 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:30:23,651 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:30:23,860 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:30:23,861 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 13:44:46,891 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 13:44:47,660 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:45:36,718 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:46:11,807 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\utils\converters.py changed, reloading.
INFO 2022-07-03 13:46:12,097 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:47:12,758 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\utils\converters.py changed, reloading.
INFO 2022-07-03 13:47:13,040 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:47:16,603 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:47:26,566 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:47:26,725 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:47:26,725 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 13:47:36,450 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 13:48:05,262 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 13:48:05,461 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 13:48:05,461 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 14:03:25,158 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:03:25,904 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:05:44,882 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:06:00,567 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 14:06:00,766 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 14:06:00,766 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
WARNING 2022-07-03 14:07:39,569 log 241 Not Found: /info/
WARNING 2022-07-03 14:07:39,570 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:07:39,570 basehttp 187 "GET /info/ HTTP/1.1" 404 3137
WARNING 2022-07-03 14:07:39,570 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3173
WARNING 2022-07-03 14:07:48,454 log 241 Not Found: /info/
WARNING 2022-07-03 14:07:48,455 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:07:48,455 basehttp 187 "GET /info/ HTTP/1.1" 404 3137
WARNING 2022-07-03 14:07:48,455 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3173
WARNING 2022-07-03 14:07:53,942 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:07:53,943 log 241 Not Found: /info/
WARNING 2022-07-03 14:07:53,943 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3173
WARNING 2022-07-03 14:07:53,944 basehttp 187 "GET /info/ HTTP/1.1" 404 3137
WARNING 2022-07-03 14:07:56,583 log 241 Not Found: /info/
WARNING 2022-07-03 14:07:56,584 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:07:56,584 basehttp 187 "GET /info/ HTTP/1.1" 404 3137
WARNING 2022-07-03 14:07:56,584 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3173
WARNING 2022-07-03 14:08:04,564 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 14:08:04,564 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3161
INFO 2022-07-03 14:08:28,779 basehttp 187 "OPTIONS /logout/ HTTP/1.1" 200 0
WARNING 2022-07-03 14:08:28,784 log 241 Not Found: /logout/
WARNING 2022-07-03 14:08:28,784 basehttp 187 "DELETE /logout/ HTTP/1.1" 404 3146
WARNING 2022-07-03 14:08:29,852 log 241 Not Found: /logout/
WARNING 2022-07-03 14:08:29,852 basehttp 187 "DELETE /logout/ HTTP/1.1" 404 3146
INFO 2022-07-03 14:09:05,988 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:09:06,288 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:13:02,681 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:13:20,777 basehttp 187 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2022-07-03 14:13:33,557 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:14:13,721 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:14:14,038 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:14:45,787 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:14:53,772 basehttp 187 "DELETE /logout/ HTTP/1.1" 200 27
WARNING 2022-07-03 14:14:57,766 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 14:14:57,766 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3315
INFO 2022-07-03 14:26:17,901 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:26:18,335 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:28:31,961 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:28:32,362 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:29:31,112 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:29:31,494 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:30:15,745 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:30:16,113 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:30:51,130 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:30:51,557 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:31:08,335 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-07-03 14:31:08,731 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:31:41,718 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-07-03 14:31:42,063 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:32:13,031 basehttp 187 "GET /info/ HTTP/1.1" 302 0
WARNING 2022-07-03 14:32:13,039 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:32:13,039 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
WARNING 2022-07-03 14:32:13,069 log 241 Not Found: /accounts/login/
WARNING 2022-07-03 14:32:13,069 basehttp 187 "GET /accounts/login/?next=/info/ HTTP/1.1" 404 3485
INFO 2022-07-03 14:32:40,503 basehttp 187 "GET /info/ HTTP/1.1" 302 0
WARNING 2022-07-03 14:32:40,504 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:32:40,505 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
WARNING 2022-07-03 14:32:40,530 log 241 Not Found: /accounts/login/
WARNING 2022-07-03 14:32:40,530 basehttp 187 "GET /accounts/login/?next=/info/ HTTP/1.1" 404 3485
INFO 2022-07-03 14:32:46,932 basehttp 187 "GET /info/ HTTP/1.1" 302 0
WARNING 2022-07-03 14:32:46,932 log 241 Not Found: /browse_histories/
WARNING 2022-07-03 14:32:46,934 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
WARNING 2022-07-03 14:32:46,954 log 241 Not Found: /accounts/login/
WARNING 2022-07-03 14:32:46,955 basehttp 187 "GET /accounts/login/?next=/info/ HTTP/1.1" 404 3485
INFO 2022-07-03 14:33:13,652 basehttp 187 "GET /info/ HTTP/1.1" 302 0
WARNING 2022-07-03 14:33:13,661 log 241 Not Found: /accounts/login/
WARNING 2022-07-03 14:33:13,661 basehttp 187 "GET /accounts/login/?next=/info/ HTTP/1.1" 404 3485
WARNING 2022-07-03 14:33:13,848 log 241 Not Found: /favicon.ico
WARNING 2022-07-03 14:33:13,848 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 3461
INFO 2022-07-03 14:33:32,860 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-03 14:33:33,041 log 241 Not Found: /carts/simple/
WARNING 2022-07-03 14:33:33,042 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
INFO 2022-07-03 14:33:38,768 basehttp 187 "GET /info HTTP/1.1" 301 0
INFO 2022-07-03 14:33:38,774 basehttp 187 "GET /info/ HTTP/1.1" 200 27
INFO 2022-07-03 14:38:46,691 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-03 14:38:47,099 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:41:51,141 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-03 14:41:57,459 basehttp 187 "GET /info/ HTTP/1.1" 200 27
INFO 2022-07-03 14:41:59,324 basehttp 187 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2022-07-03 14:42:02,067 basehttp 187 "GET /info/ HTTP/1.1" 200 45
INFO 2022-07-04 13:06:01,775 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 13:06:20,154 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:06:20,154 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:48:42,082 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:48:42,083 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
INFO 2022-07-04 13:48:43,190 basehttp 187 "GET /info/ HTTP/1.1" 200 45
WARNING 2022-07-04 13:48:43,193 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 13:48:43,193 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
INFO 2022-07-04 13:48:53,339 basehttp 187 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2022-07-04 13:48:53,477 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-04 13:48:53,660 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:48:53,661 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:49:04,858 log 241 Not Found: /
WARNING 2022-07-04 13:49:04,859 basehttp 187 "GET / HTTP/1.1" 404 3410
WARNING 2022-07-04 13:49:05,045 log 241 Not Found: /favicon.ico
WARNING 2022-07-04 13:49:05,045 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 3461
WARNING 2022-07-04 13:49:12,156 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:49:12,156 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:49:16,168 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:49:16,168 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
INFO 2022-07-04 13:49:52,899 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 13:50:04,141 basehttp 187 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2022-07-04 13:50:17,171 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-04 13:50:17,432 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:50:17,433 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:50:36,106 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:50:36,106 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
INFO 2022-07-04 13:51:24,556 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 13:51:25,540 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 13:51:45,607 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 13:51:46,657 basehttp 187 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2022-07-04 13:51:46,777 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-04 13:51:46,957 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:51:46,958 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:51:57,768 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:51:57,768 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:51:59,369 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:51:59,370 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
INFO 2022-07-04 13:53:07,839 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 13:53:18,369 basehttp 187 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-07-04 13:53:18,542 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:53:18,543 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:53:20,206 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:53:20,207 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:53:27,129 log 241 Not Found: /carts/simple/
WARNING 2022-07-04 13:53:27,129 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3467
WARNING 2022-07-04 13:53:29,201 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 13:53:29,202 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
INFO 2022-07-04 13:53:29,203 basehttp 187 "GET /info/ HTTP/1.1" 200 27
INFO 2022-07-04 13:56:40,827 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\models.py changed, reloading.
INFO 2022-07-04 13:56:41,241 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 13:57:36,621 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 14:05:13,539 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\models.py changed, reloading.
INFO 2022-07-04 14:05:13,915 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 14:06:38,231 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 14:06:42,438 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 14:06:42,440 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
INFO 2022-07-04 14:06:42,443 basehttp 187 "GET /info/ HTTP/1.1" 200 126
WARNING 2022-07-04 14:06:51,891 log 241 Not Found: /addresses/
WARNING 2022-07-04 14:06:51,892 log 241 Not Found: /areas/
WARNING 2022-07-04 14:06:51,893 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3458
WARNING 2022-07-04 14:06:51,893 basehttp 187 "GET /areas/ HTTP/1.1" 404 3446
WARNING 2022-07-04 14:07:07,996 log 241 Not Found: /addresses/
WARNING 2022-07-04 14:07:07,996 log 241 Not Found: /areas/
WARNING 2022-07-04 14:07:07,997 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3458
WARNING 2022-07-04 14:07:07,997 basehttp 187 "GET /areas/ HTTP/1.1" 404 3446
WARNING 2022-07-04 14:07:12,584 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 14:07:12,585 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3479
INFO 2022-07-04 14:07:12,586 basehttp 187 "GET /info/ HTTP/1.1" 200 126
INFO 2022-07-04 14:32:53,029 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 14:33:02,378 basehttp 187 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2022-07-04 14:33:02,423 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 14:33:26,809 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 14:33:30,353 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 14:33:30,356 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 14:33:30,363 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 14:33:52,269 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-04 14:34:00,107 log 241 Not Found: /browse_histories/
INFO 2022-07-04 14:34:00,109 basehttp 187 "GET /info/ HTTP/1.1" 200 143
WARNING 2022-07-04 14:34:00,109 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 14:59:14,629 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 14:59:18,846 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:01:15,193 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 15:01:15,571 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:02:26,496 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:02:29,428 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:02:29,429 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:02:29,433 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:02:31,803 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:05:09,097 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:05:14,292 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:05:14,294 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:05:14,301 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:05:37,798 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:06:59,200 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:07:02,219 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:07:40,823 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\celery_handler\email\tasks.py changed, reloading.
INFO 2022-07-04 15:07:41,235 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:08:13,871 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:08:21,731 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:08:21,732 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:08:21,733 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:08:22,520 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:09:25,711 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:09:28,120 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:09:28,121 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:09:28,134 basehttp 187 "GET /info/ HTTP/1.1" 200 143
ERROR 2022-07-04 15:09:30,279 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    status = send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:09:30,282 basehttp 187 "PUT /emails/ HTTP/1.1" 500 116929
INFO 2022-07-04 15:11:24,442 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:11:24,847 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:11:33,614 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:11:37,230 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    status = send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 76, in send_mail
    connection = connection or get_connection(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 50, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    import_module(module_path)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.core.mail.backend'
ERROR 2022-07-04 15:11:37,232 basehttp 187 "PUT /emails/ HTTP/1.1" 500 121327
INFO 2022-07-04 15:12:51,996 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:12:52,401 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:14:49,838 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:14:50,266 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:14:58,744 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:14:59,133 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:15:43,579 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:15:47,746 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:15:47,748 basehttp 187 "PUT /emails/ HTTP/1.1" 500 117021
INFO 2022-07-04 15:16:44,480 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:16:48,093 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:16:48,095 basehttp 187 "PUT /emails/ HTTP/1.1" 500 117106
INFO 2022-07-04 15:16:57,296 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 15:16:57,690 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:17:24,724 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:17:25,144 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:17:31,663 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:17:32,045 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:17:41,620 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:17:42,019 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:17:56,757 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:17:57,173 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:18:31,376 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 15:18:31,788 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:18:39,301 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 15:18:39,683 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:18:49,225 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:18:54,183 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:18:54,185 basehttp 187 "PUT /emails/ HTTP/1.1" 500 116954
INFO 2022-07-04 15:20:58,748 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:21:03,935 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:21:03,938 basehttp 187 "PUT /emails/ HTTP/1.1" 500 117018
INFO 2022-07-04 15:21:45,006 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:21:50,676 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:21:50,677 basehttp 187 "PUT /emails/ HTTP/1.1" 500 116978
INFO 2022-07-04 15:23:26,768 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-04 15:23:30,485 log 241 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 132, in put
    send_mail(from_email=from_email,
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 87, in send_mail
    return mail.send()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
ERROR 2022-07-04 15:23:30,487 basehttp 187 "PUT /emails/ HTTP/1.1" 500 116978
INFO 2022-07-04 15:28:32,244 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\meiduo_market\settings.py changed, reloading.
INFO 2022-07-04 15:28:32,654 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:29:23,353 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:29:45,476 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:29:54,479 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:30:41,295 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-04 15:30:41,671 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:30:52,218 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:30:52,219 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:30:52,222 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:30:53,108 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:31:10,808 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:31:22,541 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:31:22,543 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:31:22,545 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:31:23,285 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:32:53,885 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:33:14,439 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-04 15:34:16,930 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:34:23,337 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:34:23,338 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:34:23,341 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:34:24,420 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-04 15:34:54,231 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:34:54,232 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:34:54,232 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:34:55,081 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-04 15:36:28,698 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-04 15:36:54,401 log 241 Not Found: /browse_histories/
WARNING 2022-07-04 15:36:54,403 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-04 15:36:54,405 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-04 15:36:54,972 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 14:07:08,426 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-06 14:08:04,781 log 241 Not Found: /carts/simple/
WARNING 2022-07-06 14:08:04,782 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3621
WARNING 2022-07-06 14:08:06,930 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:08:06,931 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:08:06,943 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:08:08,392 basehttp 187 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2022-07-06 14:08:08,605 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 14:09:50,583 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\celery_handler\email\tasks.py changed, reloading.
INFO 2022-07-06 14:09:51,029 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:10:52,527 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-06 14:10:56,917 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:10:56,918 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:10:56,922 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:10:58,140 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:11:34,547 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:11:34,547 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:11:34,558 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:11:35,136 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:11:50,757 log 241 Not Found: /carts/simple/
WARNING 2022-07-06 14:11:50,757 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3621
INFO 2022-07-06 14:17:26,006 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\celery_handler\email\tasks.py changed, reloading.
INFO 2022-07-06 14:17:26,410 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-06 14:21:07,983 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:21:07,984 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:21:07,996 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:21:08,909 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:22:10,847 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:22:10,848 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:22:10,849 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:22:11,536 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:22:12,458 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:22:12,458 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:22:12,459 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:22:14,081 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:22:14,991 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:22:14,992 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:22:14,993 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:22:15,674 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 14:22:16,976 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:22:16,977 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3633
INFO 2022-07-06 14:22:16,977 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:32:33,564 basehttp 187 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzQ5MzUsImVtYWlsIjoiMjQ0OTQzOTU2MUBxcS5jb20ifQ.lFrRueRU3hgoyjpbZa5MTHyfDeMpsIFhYF7znWwvIlA HTTP/1.1" 200 0
WARNING 2022-07-06 14:32:33,569 log 241 Not Found: /emails/verification/
WARNING 2022-07-06 14:32:33,569 basehttp 187 "PUT /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzQ5MzUsImVtYWlsIjoiMjQ0OTQzOTU2MUBxcS5jb20ifQ.lFrRueRU3hgoyjpbZa5MTHyfDeMpsIFhYF7znWwvIlA HTTP/1.1" 404 3792
INFO 2022-07-06 14:32:42,948 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\celery_handler\email\tasks.py changed, reloading.
INFO 2022-07-06 14:32:43,351 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:33:35,999 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:33:36,383 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:35:51,102 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\urls.py changed, reloading.
INFO 2022-07-06 14:35:51,487 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:36:35,105 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\urls.py changed, reloading.
INFO 2022-07-06 14:36:35,473 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:39:09,263 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\urls.py changed, reloading.
INFO 2022-07-06 14:39:09,643 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:40:52,770 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:40:53,176 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:41:42,846 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:41:43,249 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:42:09,366 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:42:09,737 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:42:29,670 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:42:30,057 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:44:51,485 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:44:51,868 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:46:26,831 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:46:27,211 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:47:32,075 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:47:32,495 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:48:39,450 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:48:39,833 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:48:45,202 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\verifications\views.py changed, reloading.
INFO 2022-07-06 14:48:45,613 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:49:34,991 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:49:35,353 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:51:07,879 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:51:08,255 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:51:32,089 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:51:32,457 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:52:02,437 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:52:02,817 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:52:11,324 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:52:23,573 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:52:31,370 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:52:36,768 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 14:53:00,488 basehttp 187 "GET /info/ HTTP/1.1" 200 143
WARNING 2022-07-06 14:53:00,494 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:53:00,494 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-06 14:53:01,215 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 14:54:24,676 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:54:25,780 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-06 14:56:05,900 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-06 14:56:06,977 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-06 14:56:12,435 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 14:56:12,437 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-06 14:56:12,441 basehttp 187 "GET /info/ HTTP/1.1" 200 143
INFO 2022-07-06 14:56:13,324 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 14:56:22,150 basehttp 187 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzY5NzMsImlkIjo0fQ.DGiRR9sZ7BSor_let69oa0zEpzJbJVz6j56IE2H1rq0 HTTP/1.1" 200 0
INFO 2022-07-06 14:57:22,046 basehttp 187 "PUT /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzY5NzMsImlkIjo0fQ.DGiRR9sZ7BSor_let69oa0zEpzJbJVz6j56IE2H1rq0 HTTP/1.1" 200 27
INFO 2022-07-06 14:57:25,812 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-06 15:02:04,284 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 15:02:04,285 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-06 15:02:04,288 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-06 15:04:38,501 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 15:04:38,502 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-06 15:04:38,503 basehttp 187 "GET /info/ HTTP/1.1" 200 125
INFO 2022-07-06 15:04:42,030 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2022-07-06 15:05:47,663 log 241 Not Found: /browse_histories/
WARNING 2022-07-06 15:05:47,663 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-06 15:05:47,673 basehttp 187 "GET /info/ HTTP/1.1" 200 126
INFO 2022-07-06 15:05:50,045 basehttp 187 "PUT /emails/ HTTP/1.1" 200 27
INFO 2022-07-06 15:05:59,544 basehttp 187 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzc1NTAsImlkIjo0fQ.uwAoft3P65_p16NWsSc88Z6zXO-PelTX3D-MDUmYJ28 HTTP/1.1" 200 0
INFO 2022-07-06 15:05:59,551 basehttp 187 "PUT /emails/verification/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcxNzc1NTAsImlkIjo0fQ.uwAoft3P65_p16NWsSc88Z6zXO-PelTX3D-MDUmYJ28 HTTP/1.1" 200 27
WARNING 2022-07-06 15:06:02,168 log 241 Not Found: /browse_histories/
INFO 2022-07-06 15:06:02,169 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-06 15:06:02,169 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-09 13:14:22,029 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-09 13:14:27,062 log 241 Not Found: /carts/simple/
WARNING 2022-07-09 13:14:27,063 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3788
WARNING 2022-07-09 13:14:28,956 log 241 Not Found: /browse_histories/
WARNING 2022-07-09 13:14:28,957 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3800
INFO 2022-07-09 13:14:28,960 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-09 13:14:30,421 log 241 Not Found: /areas/
WARNING 2022-07-09 13:14:30,423 log 241 Not Found: /addresses/
WARNING 2022-07-09 13:14:30,423 basehttp 187 "GET /areas/ HTTP/1.1" 404 3767
WARNING 2022-07-09 13:14:30,423 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3779
INFO 2022-07-09 13:35:54,778 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-09 13:36:05,176 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 13:08:30,519 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 13:08:43,847 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-14 13:09:07,028 log 241 Not Found: /carts/simple/
WARNING 2022-07-14 13:09:07,029 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 3941
WARNING 2022-07-14 13:09:08,663 log 241 Not Found: /browse_histories/
WARNING 2022-07-14 13:09:08,663 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 3953
INFO 2022-07-14 13:09:08,672 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-14 13:09:10,198 log 241 Not Found: /addresses/
WARNING 2022-07-14 13:09:10,198 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3932
ERROR 2022-07-14 13:09:10,237 log 241 Internal Server Error: /areas/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\areas\views.py", line 10, in get
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'province_list': provinces})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
ERROR 2022-07-14 13:09:10,239 basehttp 187 "GET /areas/ HTTP/1.1" 500 106749
INFO 2022-07-14 13:09:23,663 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-14 13:09:30,768 log 241 Not Found: /addresses/
WARNING 2022-07-14 13:09:30,770 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3932
ERROR 2022-07-14 13:09:43,316 log 241 Internal Server Error: /areas/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\areas\views.py", line 10, in get
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'province_list': provinces})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
ERROR 2022-07-14 13:09:43,321 basehttp 187 "GET /areas/ HTTP/1.1" 500 123067
INFO 2022-07-14 13:10:54,445 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-14 13:10:55,892 log 241 Not Found: /addresses/
WARNING 2022-07-14 13:10:55,894 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3932
INFO 2022-07-14 13:11:41,104 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-14 13:11:42,583 log 241 Not Found: /addresses/
WARNING 2022-07-14 13:11:42,585 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3932
INFO 2022-07-14 13:15:39,826 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-14 13:15:41,824 log 241 Not Found: /addresses/
WARNING 2022-07-14 13:15:41,825 basehttp 187 "GET /addresses/ HTTP/1.1" 404 3932
INFO 2022-07-14 13:15:52,257 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2022-07-14 13:16:03,468 log 241 Not Found: /areas/140000/
WARNING 2022-07-14 13:16:03,469 basehttp 187 "GET /areas/140000/ HTTP/1.1" 404 3941
INFO 2022-07-14 13:16:08,328 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 13:16:59,771 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\areas\views.py changed, reloading.
INFO 2022-07-14 13:17:00,146 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 13:17:58,906 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 14:40:24,238 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-14 14:40:27,312 basehttp 187 "GET /areas/140000/ HTTP/1.1" 200 557
INFO 2022-07-14 14:40:28,817 basehttp 187 "GET /areas/140100/ HTTP/1.1" 200 529
INFO 2022-07-14 14:41:05,884 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-14 14:41:06,834 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
INFO 2022-07-15 14:13:15,429 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-15 14:13:41,489 log 241 Not Found: /carts/simple/
WARNING 2022-07-15 14:13:41,490 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 4114
WARNING 2022-07-15 14:13:42,929 log 241 Not Found: /browse_histories/
WARNING 2022-07-15 14:13:42,934 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 4126
INFO 2022-07-15 14:13:42,940 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-15 14:13:44,186 log 241 Not Found: /addresses/
WARNING 2022-07-15 14:13:44,187 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4105
INFO 2022-07-15 14:14:04,813 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2022-07-15 14:14:16,249 log 241 Not Found: /addresses/
WARNING 2022-07-15 14:14:16,249 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4105
INFO 2022-07-15 14:14:32,421 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-15 14:14:45,800 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:15:44,480 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-15 14:15:47,222 log 241 Not Found: /addresses/
WARNING 2022-07-15 14:15:47,223 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4105
INFO 2022-07-15 14:15:51,663 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-15 14:16:03,814 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:16:17,852 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
WARNING 2022-07-15 14:16:21,100 log 241 Not Found: /addresses/
WARNING 2022-07-15 14:16:21,101 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4105
INFO 2022-07-15 14:16:24,380 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-15 14:16:30,601 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:16:30,606 basehttp 187 "GET /areas/140000/ HTTP/1.1" 200 557
INFO 2022-07-15 14:16:49,252 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:16:54,767 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-15 14:16:55,008 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
INFO 2022-07-15 14:16:58,227 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2022-07-15 14:16:58,230 log 241 Not Found: /addresses/
WARNING 2022-07-15 14:16:58,230 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4105
INFO 2022-07-15 14:17:00,823 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:17:01,960 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
INFO 2022-07-15 14:17:03,968 basehttp 187 "GET /areas/120000/ HTTP/1.1" 200 97
INFO 2022-07-15 14:17:04,817 basehttp 187 "GET /areas/120100/ HTTP/1.1" 200 793
INFO 2022-07-16 14:20:36,568 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:21:19,139 basehttp 187 "GET /info HTTP/1.1" 301 0
INFO 2022-07-16 14:21:19,166 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-16 14:21:19,316 log 241 Not Found: /favicon.ico
WARNING 2022-07-16 14:21:19,316 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 4272
WARNING 2022-07-16 14:21:28,682 log 241 Not Found: /
WARNING 2022-07-16 14:21:28,682 basehttp 187 "GET / HTTP/1.1" 404 4221
WARNING 2022-07-16 14:21:34,730 log 241 Not Found: /carts/simple/
WARNING 2022-07-16 14:21:34,731 basehttp 187 "GET /carts/simple/ HTTP/1.1" 404 4278
WARNING 2022-07-16 14:21:36,664 log 241 Not Found: /browse_histories/
WARNING 2022-07-16 14:21:36,665 basehttp 187 "GET /browse_histories/ HTTP/1.1" 404 4290
INFO 2022-07-16 14:21:36,665 basehttp 187 "GET /info/ HTTP/1.1" 200 142
WARNING 2022-07-16 14:21:47,218 log 241 Not Found: /addresses/
WARNING 2022-07-16 14:21:47,219 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4269
INFO 2022-07-16 14:21:47,221 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:21:56,044 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-16 14:21:57,186 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
INFO 2022-07-16 14:22:20,926 basehttp 187 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
WARNING 2022-07-16 14:22:20,930 base 122 Method Not Allowed (POST): /addresses/create/
WARNING 2022-07-16 14:22:20,931 log 241 Method Not Allowed: /addresses/create/
WARNING 2022-07-16 14:22:20,931 basehttp 187 "POST /addresses/create/ HTTP/1.1" 405 0
INFO 2022-07-16 14:22:39,665 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-07-16 14:22:42,801 base 122 Method Not Allowed (POST): /addresses/create/
WARNING 2022-07-16 14:22:42,801 log 241 Method Not Allowed: /addresses/create/
WARNING 2022-07-16 14:22:42,802 basehttp 187 "POST /addresses/create/ HTTP/1.1" 405 0
INFO 2022-07-16 14:22:55,122 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:23:59,631 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:24:00,386 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:25:19,903 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:25:20,642 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:26:03,015 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-16 14:26:18,068 log 241 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 212, in post
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'address': address})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2022-07-16 14:26:18,073 basehttp 187 "POST /addresses/create/ HTTP/1.1" 500 128550
WARNING 2022-07-16 14:27:32,990 log 241 Not Found: /addresses/
WARNING 2022-07-16 14:27:32,991 basehttp 187 "GET /addresses/ HTTP/1.1" 404 4269
INFO 2022-07-16 14:27:38,675 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:29:02,637 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:29:02,939 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:29:12,319 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:29:12,588 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:29:15,832 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:29:16,102 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:30:10,391 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-07-16 14:30:10,665 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:30:18,029 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:30:18,371 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:30:31,856 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:30:32,176 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:31:58,199 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:31:58,500 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:32:18,105 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:32:18,395 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:32:40,059 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:32:40,359 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:32:47,683 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:32:47,963 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:33:28,979 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:33:29,249 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:35:17,633 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:35:17,923 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:35:29,062 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:35:30,906 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
ERROR 2022-07-16 14:35:30,932 log 241 Internal Server Error: /addresses/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 234, in get
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'addresses': address_list})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2022-07-16 14:35:30,934 basehttp 187 "GET /addresses/ HTTP/1.1" 500 110918
INFO 2022-07-16 14:35:32,117 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
ERROR 2022-07-16 14:35:32,136 log 241 Internal Server Error: /addresses/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 234, in get
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'addresses': address_list})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2022-07-16 14:35:32,138 basehttp 187 "GET /addresses/ HTTP/1.1" 500 110918
INFO 2022-07-16 14:35:54,511 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:36:41,788 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
ERROR 2022-07-16 14:36:41,843 log 241 Internal Server Error: /addresses/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 234, in get
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'addresses': address_list})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2022-07-16 14:36:41,847 basehttp 187 "GET /addresses/ HTTP/1.1" 500 127236
INFO 2022-07-16 14:37:07,124 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:37:07,889 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:37:13,347 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:37:17,042 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:37:17,045 basehttp 187 "GET /addresses/ HTTP/1.1" 200 209
INFO 2022-07-16 14:38:22,966 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:38:24,664 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:38:24,669 basehttp 187 "GET /addresses/ HTTP/1.1" 200 251
INFO 2022-07-16 14:38:43,313 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-16 14:38:44,540 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
ERROR 2022-07-16 14:38:59,886 log 241 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 212, in post
    return JsonResponse({'code': 0, 'errmsg': 'ok', 'address': address})
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 653, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2022-07-16 14:38:59,888 basehttp 187 "POST /addresses/create/ HTTP/1.1" 500 114109
INFO 2022-07-16 14:39:20,923 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:39:49,282 basehttp 187 "POST /addresses/create/ HTTP/1.1" 200 361
INFO 2022-07-16 14:39:49,371 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:39:49,376 basehttp 187 "GET /addresses/ HTTP/1.1" 200 574
INFO 2022-07-16 14:40:05,161 basehttp 187 "OPTIONS /addresses/1/default/ HTTP/1.1" 200 0
WARNING 2022-07-16 14:40:05,167 log 241 Not Found: /addresses/1/default/
WARNING 2022-07-16 14:40:05,167 basehttp 187 "PUT /addresses/1/default/ HTTP/1.1" 404 4456
INFO 2022-07-16 14:40:06,031 basehttp 187 "OPTIONS /addresses/3/default/ HTTP/1.1" 200 0
WARNING 2022-07-16 14:40:06,037 log 241 Not Found: /addresses/3/default/
WARNING 2022-07-16 14:40:06,037 basehttp 187 "PUT /addresses/3/default/ HTTP/1.1" 404 4456
INFO 2022-07-16 14:49:14,368 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\urls.py changed, reloading.
INFO 2022-07-16 14:49:14,666 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:53:26,304 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:53:58,060 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:54:46,328 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\models.py changed, reloading.
INFO 2022-07-16 14:54:46,611 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:58:10,471 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 14:58:10,771 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:59:07,742 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 14:59:11,149 basehttp 187 "PUT /addresses/1/default/ HTTP/1.1" 200 27
INFO 2022-07-16 14:59:11,237 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:59:11,241 basehttp 187 "GET /addresses/ HTTP/1.1" 200 574
INFO 2022-07-16 14:59:25,642 basehttp 187 "PUT /addresses/3/default/ HTTP/1.1" 200 27
INFO 2022-07-16 14:59:25,728 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 14:59:25,733 basehttp 187 "GET /addresses/ HTTP/1.1" 200 574
INFO 2022-07-16 15:00:40,028 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 15:00:40,320 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:01:09,802 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:01:12,140 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 15:01:12,146 basehttp 187 "GET /addresses/ HTTP/1.1" 200 624
INFO 2022-07-16 15:02:13,692 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:02:15,608 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 15:02:15,614 basehttp 187 "GET /addresses/ HTTP/1.1" 200 599
INFO 2022-07-16 15:02:19,488 basehttp 187 "PUT /addresses/1/default/ HTTP/1.1" 200 27
INFO 2022-07-16 15:02:19,557 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 15:02:19,561 basehttp 187 "GET /addresses/ HTTP/1.1" 200 599
INFO 2022-07-16 15:03:57,318 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 15:03:57,628 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:06:59,119 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:07:06,572 basehttp 187 "OPTIONS /addresses/1/ HTTP/1.1" 200 0
ERROR 2022-07-16 15:07:06,599 log 241 Internal Server Error: /addresses/1/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.users.views.view didn't return an HttpResponse object. It returned None instead.
ERROR 2022-07-16 15:07:06,601 basehttp 187 "DELETE /addresses/1/ HTTP/1.1" 500 68667
INFO 2022-07-16 15:07:43,492 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:07:45,105 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 15:07:45,111 basehttp 187 "GET /addresses/ HTTP/1.1" 200 599
INFO 2022-07-16 15:08:17,579 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:09:27,383 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:10:02,821 basehttp 187 "DELETE /addresses/1/ HTTP/1.1" 200 27
INFO 2022-07-16 15:10:02,928 basehttp 187 "GET /addresses/ HTTP/1.1" 200 599
INFO 2022-07-16 15:10:04,796 basehttp 187 "GET /addresses/ HTTP/1.1" 200 599
INFO 2022-07-16 15:10:29,736 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:10:40,491 basehttp 187 "DELETE /addresses/1/ HTTP/1.1" 200 27
INFO 2022-07-16 15:10:40,590 basehttp 187 "GET /addresses/ HTTP/1.1" 200 390
INFO 2022-07-16 15:10:42,802 basehttp 187 "GET /addresses/ HTTP/1.1" 200 390
INFO 2022-07-16 15:11:18,757 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 15:11:19,495 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:12:55,257 basehttp 187 "GET /addresses/ HTTP/1.1" 200 393
INFO 2022-07-16 15:13:02,208 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:13:20,887 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 15:13:21,160 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:14:02,181 autoreload 266 C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py changed, reloading.
INFO 2022-07-16 15:14:02,450 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:17:17,824 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:17:26,618 basehttp 187 "OPTIONS /addresses/3/title/ HTTP/1.1" 200 0
INFO 2022-07-16 15:17:45,452 basehttp 187 "PUT /addresses/3/title/ HTTP/1.1" 200 27
INFO 2022-07-16 15:17:50,499 basehttp 187 "GET /areas/ HTTP/1.1" 200 1772
INFO 2022-07-16 15:17:50,506 basehttp 187 "GET /addresses/ HTTP/1.1" 200 393
INFO 2022-07-16 15:25:07,468 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:25:15,679 basehttp 187 "GET /areas/310000/ HTTP/1.1" 200 97
INFO 2022-07-16 15:25:16,997 basehttp 187 "GET /areas/310100/ HTTP/1.1" 200 793
INFO 2022-07-16 15:25:34,096 basehttp 187 "OPTIONS /addresses/3/ HTTP/1.1" 200 0
INFO 2022-07-16 15:27:58,837 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:31:54,125 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-16 15:32:14,046 log 241 Internal Server Error: /addresses/3/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1988, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 293, in put
    address.save()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 970, in _save_table
    updated = self._do_update(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 1034, in _do_update
    return filtered._update(values) > 0
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 885, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1783, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1348, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\compiler.py", line 50, in as_sql
    update_query, update_params = super().as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1749, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\related.py", line 1126, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 910, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 2668, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1990, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got (310000,).
ERROR 2022-07-16 15:32:14,054 basehttp 187 "PUT /addresses/3/ HTTP/1.1" 500 168725
INFO 2022-07-16 15:33:22,729 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-16 15:33:31,529 log 241 Internal Server Error: /addresses/3/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1988, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 293, in put
    address.save()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 970, in _save_table
    updated = self._do_update(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 1034, in _do_update
    return filtered._update(values) > 0
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 885, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1783, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1348, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\compiler.py", line 50, in as_sql
    update_query, update_params = super().as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1749, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\related.py", line 1126, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 910, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 2668, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1990, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got (310000,).
ERROR 2022-07-16 15:33:31,534 basehttp 187 "PUT /addresses/3/ HTTP/1.1" 500 168728
INFO 2022-07-16 15:33:53,502 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-07-16 15:34:38,504 log 241 Internal Server Error: /addresses/3/
Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1988, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HJX\PycharmProjects\meiduo_market\apps\users\views.py", line 293, in put
    address.save()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 970, in _save_table
    updated = self._do_update(
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 1034, in _do_update
    return filtered._update(values) > 0
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 885, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1783, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1348, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\compiler.py", line 50, in as_sql
    update_query, update_params = super().as_sql()
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1749, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\related.py", line 1126, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 910, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 2668, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Users\HJX\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\fields\__init__.py", line 1990, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got (310000,).
ERROR 2022-07-16 15:34:38,512 basehttp 187 "PUT /addresses/3/ HTTP/1.1" 500 168728
INFO 2022-07-16 15:36:27,736 autoreload 677 Watching for file changes with StatReloader
INFO 2022-07-16 15:36:42,022 basehttp 187 "PUT /addresses/3/ HTTP/1.1" 200 344
